### ISSUE TITLE
Can't find the default.ini file.

### ISSUE THREAD

**Issue by Warmchay** [supermt/ADOC-Rocks-tracker#2]
Hi, thanks for your incredible benchmarking tools.

I want to test by using RocksDB locally, while I couldn't find the default.ini file anywhere, including RocksDB codes nor this repo.

Could you instrurt me how to find, or how to complie? Really thanks!

**Comment by Warmchay** [comment]
Writing the `default.ini` file according by `db_bench_option.py` is fine.

**Comment by Yemaoxin** [comment]
I hope this message finds you well. I wanted to provide some clarification regarding the default.ini file in this project.

As you may have noticed, the default.ini file has been intentionally excluded from the .gitignore file. Consequently, if you are unable to locate a default.ini file, it's because it hasn't been included in the repository. However, there is a simple solution – you can create one yourself.

To facilitate the creation of the default.ini file, I recommend referring to the configurations outlined in the db_bench_option.py file. This file serves as a comprehensive reference point, providing the necessary parameters and settings to include in the default.ini file.

By following the configurations in db_bench_option.py, you can ensure that the default.ini file aligns with our project requirements and serves its intended purpose. If you have any questions or need further assistance in this regard, feel free to reach out.

Thank you for your attention, and I appreciate your collaboration on this matter.

Best regards,
Maoxin

**Comment by Yemaoxin** [comment]
The reason for not uploading the default.ini file is also simple, as it needs to have the server's sudo password in it

**Comment by Yemaoxin** [comment]
Here's a simple example of default.ini, which you can modify further to suit your needs
------
default.ini
------
[Permission]
passwd=123456

[Paths]
db_bench_path="your db_bench path"

[CPU]
limit_type=-1
cpu_in_total=12

[Entry Control]
db_size=10000000

**Comment by Warmchay** [comment]
> ## Here's a simple example of default.ini, which you can modify further to suit your needs
> ## default.ini
> [Permission] passwd=123456
> 
> [Paths] db_bench_path="your db_bench path"
> 
> [CPU] limit_type=-1 cpu_in_total=12
> 
> [Entry Control] db_size=10000000

Thanks for your clear example and detailed solutions above all, it's a good way for me to rethink the structure of this project.

Really thanks again!
